eslint.config: remove redundant `@typescript-eslint` plugin
That plugin is already included in the `typescript-eslint` package,
so it is redundant to include it again in the ESLint configuration.

This change is required to avoid a warning when running ESLint:

    ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin
    "@typescript-eslint".

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>