Use the GITHUB_TOKEN to avoid exceeding the API rate limit
As of a few days ago, plenty of workflow runs in git/git,
gitgitgadget/git and git-for-windows/git failed with message like this:

	Error: API rate limit exceeded for 172.176.196.48. (But here's
	the good news: Authenticated requests get a higher rate limit.
	Check out the documentation for more details.)

So let's try this.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>